In [1]:
import torch
import pandas as pd
import numpy as np
import datasets
from load_models_and_data import load_vocabulary, load_embeddings, text_to_embeddings, calc_cosine_sim, calculate_similarities
from tqdm import tqdm
tqdm.pandas()

c:\Users\nnamd\OneDrive\Python_learning\MLX\MLX_Week2\mlx_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


API key loaded successfully


wandb: Currently logged in as: nnamdi-odozi (nnamdi-odozi-ave-actuaries) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [2]:
from datasets import load_dataset

# Loading datasets from Hugging Face
ds1 = load_dataset("cocoritzy/week_2_triplet_dataset_soft_negatives")
ds2 = load_dataset("cocoritzy/week_2_triplet_dataset_hard_negatives")


In [3]:
# Paths to your files
embeddings_path = "./downloaded_model/embeddings.pt"
vocab_path = "./downloaded_model/tkn_ids_to_words.csv"

# Load embeddings and vocabulary
print("Loading embeddings and vocabulary...")
embeddings = load_embeddings(embeddings_path)
word_to_idx = load_vocabulary(vocab_path)

print(f"Loaded embeddings with shape: {embeddings.shape}")
print(f"Loaded vocabulary with {len(word_to_idx)} tokens")

# Example usage (uncomment when ready to test)
sample_text = "This is a test sentence"
embeddings_result = text_to_embeddings(sample_text, word_to_idx, embeddings)
print(f"Embedded text shape: {embeddings_result.shape}")

# Testing - Set numpy print options
np.set_printoptions(precision=4, suppress=True, threshold=10)  # threshold limits number of elements shown
numpy_array = embeddings_result.detach().numpy()
print("Embedding array with custom formatting:")
print(numpy_array)


Loading embeddings and vocabulary...
Loaded embeddings with shape: torch.Size([63642, 128])
Loaded vocabulary with 63641 tokens
Embedded text shape: torch.Size([5, 128])
Embedding array with custom formatting:
[[ 0.1381  0.5469 -1.076  ... -0.3798 -0.7187  0.2953]
 [ 0.1925 -0.0985 -0.1367 ...  0.7328  0.5067  0.7939]
 [ 0.2072  0.043  -0.6497 ... -0.0641 -0.6588 -0.1389]
 [ 0.418  -0.645  -0.5003 ... -0.159  -0.2203 -0.2697]
 [-0.4971  0.4175 -0.0469 ... -0.1927  2.253  -0.1716]]


In [4]:
df1  = pd.DataFrame(ds1['train'])
df2  = pd.DataFrame(ds2['train'])

In [5]:
df1

query_id                                              query  \
0         19699                                        what is rba   
1         19700                       was ronald reagan a democrat   
2         19701  how long do you need for sydney and surroundin...   
3         19702                    price to install tile in shower   
4         19703                    why conversion observed in body   
...         ...                                                ...   
79699    102124                             meaning of propagation   
79700    102125  do you have to do a phd to be a clinical psych...   
79701    102126                        what wine goes with oysters   
79702    102127                what strengths does lithium come in   
79703    102128                  what is polarity index definition   

                                        positive_passage  \
0      Results-Based Accountability® (also known as R...   
1      From Wikipedia, the free encyclopedia. A Reaga...   
2      Sydney is the capital city of the Australian s...   
3      1 Install ceramic tile floor to match shower-A...   
4      Conversion disorder is a type of somatoform di...   
...                                                  ...   
79699  definition of propagation the act or action of...   
79700  The goal you choose will determine your path. ...   
79701  You may also enjoy these other types of wine w...   
79702  Lithium 150 mg. Lithium (Eskalith ® , Eskalith...   
79703  Polarity Index. Burdick & Jackson solvents are...   

                                        negative_passage  \
0      I finally found some real salary data for phys...   
1      The Pacific Ocean lies to the east while the S...   
2      Probiotics are found in foods such as yogurt, ...   
3      Iodine is critical to thyroid health and funct...   
4      The answer to the question how much does it co...   
...                                                  ...   
79699  A minimum of two credits of laboratory science...   
79700  1 The mitochondria of eukaryotes evolved from ...   
79701  Raynaud's (say ray-NOHZ) phenomenon is a probl...   
79702  While kids feel like they’ve been grownups for...   
79703  Calculating Costs Per Inmate. According to the...   

       negative_from_query_id  
0                       86595  
1                       66360  
2                       88507  
3                       87550  
4                       61479  
...                       ...  
79699                   21857  
79700                   28764  
79701                   42284  
79702                   42891  
79703                   94401  

[79704 rows x 5 columns]

In [6]:
df2

query_id                                              query  \
0         19699                                        what is rba   
1         19700                       was ronald reagan a democrat   
2         19701  how long do you need for sydney and surroundin...   
3         19702                    price to install tile in shower   
4         19703                    why conversion observed in body   
...         ...                                                ...   
79695    102124                             meaning of propagation   
79696    102125  do you have to do a phd to be a clinical psych...   
79697    102126                        what wine goes with oysters   
79698    102127                what strengths does lithium come in   
79699    102128                  what is polarity index definition   

                                        positive_passage  \
0      Results-Based Accountability® (also known as R...   
1      From Wikipedia, the free encyclopedia. A Reaga...   
2      Sydney is the capital city of the Australian s...   
3      1 Install ceramic tile floor to match shower-A...   
4      Conversion disorder is a type of somatoform di...   
...                                                  ...   
79695  definition of propagation the act or action of...   
79696  The goal you choose will determine your path. ...   
79697  You may also enjoy these other types of wine w...   
79698  Lithium 150 mg. Lithium (Eskalith ® , Eskalith...   
79699  Polarity Index. Burdick & Jackson solvents are...   

                                        negative_passage  \
0      vs. NetIQ Identity Manager. Risk-based authent...   
1      1984 Re-Election. In November 1984, Ronald Rea...   
2      The Sydney central business district, Sydney h...   
3      The national average for a new shower installa...   
4      Conclusions: In adult body CT, dose to an orga...   
...                                                  ...   
79695  1 1 no object of a plant or animal reproduce b...   
79696  The Path to Becoming a Psychologist. First, yo...   
79697  If you need a wine to pair with oysters or mus...   
79698  A: Lithium is a medication that is used to tre...   
79699  Definition. noun. (1) The presence of or havin...   

       negative_index_in_group  
0                            8  
1                            7  
2                            3  
3                            8  
4                            1  
...                        ...  
79695                        3  
79696                        1  
79697                        1  
79698                        8  
79699                        5  

[79700 rows x 5 columns]

In [8]:
embedded_query = text_to_embeddings(df2['query'][0], word_to_idx, embeddings)
embedded_positive = text_to_embeddings(df1['positive_passage'][0], word_to_idx, embeddings)
embedded_negative = text_to_embeddings(df1['negative_passage'][0], word_to_idx, embeddings)

embedded_query.shape

torch.Size([3, 128])

In [9]:
a = embedded_query.mean(dim=0)
b = embedded_positive.mean(dim=0)
c = embedded_negative.mean(dim=0)


In [10]:
import torch.nn.functional as F

cosine_similarity = F.cosine_similarity(a, c, dim=0)
print(f"Cosine similarity between query and positive passage: {cosine_similarity.item()}")

Cosine similarity between query and positive passage: 0.7518182992935181


In [11]:

# Process the dataframe using apply
print("Calculating similarities... This may take a while depending on dataframe size.")
similarities = df1.progress_apply(
    lambda row: calculate_similarities(row, word_to_idx, embeddings), 
    axis=1
)

# Join the similarities to the dataframe
df1_with_similarities = pd.concat([df1, similarities], axis=1)

# Show a sample of the results
print(df1_with_similarities[['query_pos_sim', 'query_neg_sim', 'pos_neg_sim']].head())

print(df1_with_similarities[['query_pos_sim', 'query_neg_sim', 'pos_neg_sim']].mean())

# Calculate how often the positive passage is ranked higher than negative
higher_count = (df1_with_similarities['query_pos_sim'] > df1_with_similarities['query_neg_sim']).sum()
total = len(df1_with_similarities)
print(f"\nPositive passage ranked higher than negative: {higher_count} out of {total} ({higher_count/total:.2%})")



Calculating similarities... This may take a while depending on dataframe size.


100%|██████████| 79704/79704 [04:51<00:00, 273.42it/s]

   query_pos_sim  query_neg_sim  pos_neg_sim
0       0.746116       0.751818     0.877889
1       0.357790      -0.023197     0.585325
2       0.280621       0.223732     0.756405
3       0.282147       0.126030     0.656548
4       0.132451      -0.001793     0.705996
query_pos_sim    0.426907
query_neg_sim    0.206892
pos_neg_sim      0.688815
dtype: float64

Positive passage ranked higher than negative: 75260 out of 79704 (94.42%)


In [12]:
# Process the dataframe using apply
print("Calculating similarities... This may take a while depending on dataframe size.")
similarities = df2.progress_apply(
    lambda row: calculate_similarities(row, word_to_idx, embeddings), 
    axis=1
)

# Join the similarities to the dataframe
df2_with_similarities = pd.concat([df2, similarities], axis=1)

# Show a sample of the results
print(df2_with_similarities[['query_pos_sim', 'query_neg_sim', 'pos_neg_sim']].head())

print(df2_with_similarities[['query_pos_sim', 'query_neg_sim', 'pos_neg_sim']].mean())

# Calculate how often the positive passage is ranked higher than negative
higher_count = (df2_with_similarities['query_pos_sim'] > df2_with_similarities['query_neg_sim']).sum()
total = len(df2_with_similarities)
print(f"\nPositive passage ranked higher than negative: {higher_count} out of {total} ({higher_count/total:.2%})")



Calculating similarities... This may take a while depending on dataframe size.


100%|██████████| 79700/79700 [05:12<00:00, 254.99it/s]

   query_pos_sim  query_neg_sim  pos_neg_sim
0       0.746116       0.699165     0.847480
1       0.357790       0.228804     0.941763
2       0.280621       0.226715     0.909032
3       0.282147       0.172816     0.928545
4       0.132451       0.161791     0.773421
query_pos_sim    0.426904
query_neg_sim    0.407663
pos_neg_sim      0.847123
dtype: float64

Positive passage ranked higher than negative: 45329 out of 79700 (56.87%)
